#!/usr/bin/env bash

dir="$HOME/.config/polybar"
themes=(`ls --hide="launch.sh" $dir`)
WALLPAPER=$(cat ~/.fehbg | grep -v '#!/bin/sh' | cut -d "'" -f 2)

launch_bar() {
	# Terminate already running bar instances
	killall -q polybar

	# Wait until the processes have been shut down
	while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

	# Fix windows
    bspc config top_padding 0
    bspc config bottom_padding 0

	# Launch the bar
	polybar -q main -c "$dir/$style/config.ini" > /dev/null 2>&1 &
}

if [[ "$1" == "--trans" ]]; then
    style="trans"
	# Sudo rofi
	echo 'rofi -theme ~/.config/polybar/trans/scripts/rofi/launcher.rasi -show drun -run-command' > ~/.sudo-launch
    # Pywal
    ~/.config/polybar/trans/scripts/pywal.sh $WALLPAPER
    launch_bar

elif [[ "$1" == "--colorblocks" ]]; then
	style="colorblocks"
	# Sudo rofi
	echo 'rofi -theme ~/.config/polybar/colorblocks/scripts/rofi/launcher.rasi -show drun -run-command' > ~/.sudo-launch
	# Pywal
    ~/.config/polybar/colorblocks/scripts/pywal.sh $WALLPAPER
    launch_bar

else
	cat <<- EOF
	Usage: change-polybar --theme
		
	Available Themes:
	--colorblocks   
	--trans
	EOF
fi
