#!/usr/bin/bash

#count=`ps -ef | grep -vE "grep|vim" | grep -c "changer"`
#if [[ $count > 2 ]]; then
#    echo "[-] This script is running multiple times, killing it"
#    killall changer
#    exit
#fi

tcount=`ps -ef | grep -v grep | grep -c 'polybar -q top -c /home/.*/.config/polybar/.*/config.ini'`
bcount=`ps -ef | grep -v grep | grep -c 'polybar -q bottom -c /home/.*/.config/polybar/.*/config.ini'`
mcount=`ps -ef | grep -v grep | grep -c 'polybar -q main -c /home/.*/.config/polybar/.*/config.ini'`
if [[ $mcount > 1 || $bcount > 1 || $tcount > 1 ]]; then
    echo "[-] Multiple polybars are running, killing them"
    killall polybar
    bspc wm -r
    exit
fi

wcount=`ps -efww | grep -v "grep" | grep -c "pywal.sh"`
if [[ $wcount > 1 ]]; then
    echo "[-] Multiple pywal scripts are running, killing it"
    pid=`ps -efww | grep -v "grep" | grep "pywal.sh" | awk -vpid=$$ '$2 != pid { print $2 }'`
    for p in $pid
    do
        kill -9 $p
    done
    exit
fi

# Shuffle wallpapers
#WAL=$(ls ~/Pictures/Wallpapers/*.* | shuf -n 1)
WAL=$(find ~/Pictures/Wallpapers/ -type f -iname '*.PNG' -o -iname '*.JPG' | shuf -n 1)

# Kill video wallpapar processes
killall xwinwrap > /dev/null 2>&1
video-wallpaper.sh --stop > /dev/null 2>&1

# Kill unnecessary processes
scripts=`ps -ef | grep -v "grep" | grep ".config/polybar/.*/scripts/.*" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $scripts
do
    kill -9 $d
    wait
done

colorblocks=`ps -efww | grep -v "grep" | grep "\--colorblocks" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $colorblocks
do
    echo "[-] The colorblocks theme $d is still running, killing it"
    kill -9 $d
    wait
done
trans=`ps -efww | grep -v "grep" | grep "\--trans" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $trans
do
    echo "[-] The trans theme $d is still running, killing it"
    kill -9 $d
    wait
done

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "colorblocks" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
    ~/.config/polybar/colorblocks/scripts/pywal.sh $WAL
    #wait $!
    #/usr/bin/bash ~/.config/polybar/launch.sh --colorblocks &
    #wait $!
elif [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "trans" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
    ~/.config/polybar/trans/scripts/pywal.sh $WAL
    #wait $!
    #/usr/bin/bash ~/.config/polybar/launch.sh --shapes & 
    #wait $!
else
    echo "[-] A polybar theme is not running"
    exit
fi

# Picom Configuration
if ! pgrep -x "picom" > /dev/null
then
    picom --config ~/.config/picom/picom.conf -b
fi