#!/usr/bin/bash

function ctrl_c() {
    echo -e "\nTrapped CTRL-C\n"
    exit
}

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

ALACRITTY="$HOME/.config/alacritty/alacritty.yml"
FONT_SIZE=$(yad --scale --value=15 --min-value=5 --max-value=30 --inc-buttons)

if [ -z "$FONT_SIZE" ]
    then
        echo "The program was canceled and the font size was not changed!"
    else
        PREVIOUS_FONT_SIZE=$(cat $ALACRITTY | grep -Eo "size: [0-9]{1,2}" | sort -u)
        echo "The previous font $PREVIOUS_FONT_SIZE"
        sed -rie "s/size: ([0-9]{1,2})/size: $FONT_SIZE/g" $ALACRITTY
        echo "The new font size of alacritty is: $FONT_SIZE"
fi
