#!/usr/bin/bash

# Description: Print keyboard shortcuts.

# SXHKD Shortcuts
function sxhkd_keys {
    cat << EOF
BSPWM Mouse Keyboard Shortcuts

| Action                                         | Shortcut                |
|------------------------------------------------|-------------------------|
| Move a floating window or swap a tiled window. | alt+left mouse click    |
| Resize any tiling or floating window.          | alt+right mouse click   |
| Open jgmenu for context menu.                  | super+right mouse click |

BSPWM Keyboard Shortcuts

> Note: left,down,up,right refers to the arrow keys.

| Action                                                                          | Shortcut                                                              |
|---------------------------------------------------------------------------------|-----------------------------------------------------------------------|
| Open the terminal emulator (kitty).                                             | windows+enter                                                         |
| Open the terminal-emulator (qterminal), doesn't apply the pywal color.          | windows+ctrl+enter                                                    |
| Launch the power menu.                                                          | windows+q or alt+q                                                    |
| Close the current window.                                                       | windows+w or alt+w                                                    |
| Restart the bspwm configuration.                                                | windows+alt+r or ctrl+alt+r                                           |
| Logout from the system.                                                         | windows+alt+q or ctrl+alt+q                                           |
| Move through the windows in the current workspace.                              | windows+left,down,up,right or windows+h,j,k,l                         | 
| Open rofi and Esc to exit.                                                      | windows+d or alt+d                                                    |
| Open rofi and run commands as sudo, useful for tools such as wireshark.         | windows+ctrl+d                                                        |
| Change the workspace.                                                           | windows+1,2,3,4,5,6,7,8,9 or alt+1,2,3,4,5,6,7,8,9                    |
| Change the current window to tiling mode.                                       | windows+t or alt+t                                                    |
| Change the current window to "full" mode.                                       | windows+m or alt+m                                                    |
| Change the current window to full-screen mode                                   | windows+f or alt+f                                                    |
| Change the current window to floating mode.                                     | windows+s or alt+s                                                    |
| Move the current window to another workspace.                                   | windows+shift+1,2,3,4,5,6,7,8,9 or alt+shift+1,2,3,4,5,6,7,8,9        |
| Resize current window (only works if you are in terminal or floating mode).     | windows+alt+left,down,up,right or windows+alt+h,j,k,l                 |
| Change the position of the current window (only works in floating mode).        | windows+ctrl+left,down,up,right or windows+ctrl+h,j,k,l               |
| Show a preselection and then open a window.                                     | windows+ctrl+alt+left,down,up,right or windows+ctrl+alt+h,j,k,l       |
| Undo the preselection.                                                          | windows+ctrl+space                                                    |
| Close and kill.                                                                 | windows+shift+w or alt+shift+w                                        |
| Alternate between the tiled and monocle layout.                                 | windows+m or alt+m                                                    |
| Set the window state.                                                           | windows+shift+t,s,f or alt+shift+t,s,f                                |
| Set the node flags.                                                             | windows+ctrl+m,x,y,z                                                  |
| Focus on older or newer node in the focus history.                              | windows+o,i                                                           |
| Focus the last node/desktop.                                                    | windows+grave,Tab or alt+grave,Tab                                    |
| Focus the next/previous desktop in the current monitor.                         | windows+bracket{left,right} or windows+bracket{h,l}                   |
| Focus the next/previous window in the current desktop.                          | windows+shift+c                                                       |
| Focus the node for the given path jump.                                         | windows+p,b,comma,period                                              |
| Focus the node in the given direction (swap window).                            | windows+shift+left,down,up,right or windows+shift+h,j,k,l             |

### Special Keyboard Shortcuts

| Action                                         | Shortcut                               |
|------------------------------------------------|----------------------------------------|
| Activate the bspwm workspace preview           | windows+alt+w or ctrl+alt+p            |
| Change to a specific wallpaper using the GUI.  | windows+alt+e or ctrl+alt+e            |
| Select wallpaper with a preview                | windows+alt+x or ctrl+alt+x            |
| Change the terminal font size.                 | windows+alt+f or ctrl+alt+f            |
| Change the corners of the windows.             | windows+alt+b or ctrl+alt+b            |
| Execute the lock screen.                       | alt+shift+x                            |
| Take a screenshot with flameshot.              | print                                  |
EOF
}

# Kitty Shortcuts
function kitty_keys {
    cat << EOF 
Window Management Keyboard Shortcuts

| Action                	| Shortcut                                                                                                |
|-----------------------	|---------------------------------------------------------------------------------------------------------|
| New window            	| ctrl+shift+enter                                                                   	                  |
| New OS window         	| ctrl+shift+n                                                                       	                  |
| Close window          	| ctrl+shift+w                                                                     	                      |
| Next window           	| ctrl+shift+]                                                                                            |
| Previous window       	| ctrl+shift+[                                                                                            |
| Move window forward   	| ctrl+shift+f                                                                                            |
| Move window backward  	| ctrl+shift+b                                                                                            |
| Move window to top    	| ctrl+shift+\`                                                                                           |
| Visually focus window 	| ctrl+shift+f7                                                                                           |
| Visually swap window  	| ctrl+shift+f8                                                                                           |
| Focus specific window 	| ctrl+shift+1, ctrl+shift+2 … ctrl+shift+0 (clockwise from the top-left)	                              |

Tab Management Keyboard Shortcuts

| Action            	| Shortcut                                        	|
|-------------------	|---------------------------------------------------|
| New tab           	| ctrl+shift+t               	                    |
| Close tab         	| ctrl+shift+q               	                    |
| Next tab          	| ctrl+shift+right	                                |
| Previous tab      	| ctrl+shift+left	                                |
| Next layout       	| ctrl+shift+l                                  	|
| Move tab forward  	| ctrl+shift+.                                  	|
| Move tab backward 	| ctrl+shift+,                                  	|
| Set tab title     	| ctrl+shift+alt+t         	                        |

Layout Management Keyboard Shortcuts

| Action                                                                                                    	| Shortcut             	|
|-----------------------------------------------------------------------------------------------------------	|----------------------	|
| Next layout                                                                                               	| ctrl+shift+up      	|
| Go to layout (tall,stack, etc)                                                                            	| ctrl+shift+down    	|
| Previous layout                                                                                           	| ctrl+shift+page_up 	|
| Toggle layout (switches to the named layout or the previous layout) 	                                        | ctrl+shift+page_down  |

Scrolling Keyboard Shortcuts

| Action                    	| Shortcut             	|
|---------------------------	|----------------------	|
| Line up                   	| ctrl+shift+up      	|
| Line down                 	| ctrl+shift+down    	|
| Page up                   	| ctrl+shift+page_up 	|
| Page down                 	| ctrl+shift+page_down  |
| Top                       	| ctrl+shift+home    	|
| Bottom                    	| ctrl+shift+end     	|
| Previous shell prompt     	| ctrl+shift+z       	|
| Next shell prompt         	| ctrl+shift+x       	|
| Browse scrollback less 	    | ctrl+shift+h       	|
| Browse last cmd output    	| ctrl+shift+g       	|
EOF
}

# Neovim Shortcuts
function neovim_keys {
    cat << EOF 
Neovim Custom Shortcuts

| Action            	| Shortcut                                                     	|
|-------------------	|--------------------------------------------------------------	|
| Resize windows    	| alt+h,j,k,l (Normal Mode)                                     |
| Escape            	| jk or kj (from Insert Mode to Normal Mode)               	    |
| Save              	| ctrl+s (Normal Mode)                                       	|
| Quit              	| ctrl+q (Normal Mode)                                       	|
| Another Escape    	| ctrl+c (from Insert Mode to Normal Mode)                   	|
| Tabbing           	| mouse highlight (Visual Mode) then shift+left or shift+right 	|
| Tabs              	| tab or shift+tab (Insert Mode)                           	    |
| Window Navigation 	| ctrl+h,j,k,l (Normal Mode)                                	|
| Text Navigation   	| h,j,k,l (Normal Mode)                                      	|
EOF
}

# Help Menu
function print_help {
    cat << EOF
Usage: shortcuts [--sxhkd] [--kitty] [--neovim]
--sxhkd: Print sxhkd shortcuts.
--kitty: Print kitty shortcuts.
--neovim: Print neovim shortcuts.
--help: Print this help menu.
EOF
}

while true
    do if [ $# -gt 0 ]
        then case $1 in
        --sxhkd*)
            sxhkd_keys
            exit 0
            ;;
	    --kitty*)
            kitty_keys
            exit 0
            ;;
	    --neovim*)
            neovim_keys
            exit 0
            ;;        
        --help*)
            print_help
            exit 1
            ;;
            *)
            print_help
            exit 1
            ;;	
        esac
    else
        print_help
        exit 1
    fi
done