#!/usr/bin/bash

# Author: https://github.com/ivanbartsov
# Issue: https://github.com/davatorium/rofi/issues/584
# Modified by nozerobit

# Take password prompt from STDIN, print password to STDOUT
# the sed piece just removes the colon from the provided
# prompt: rofi -p already gives us a colon

# Kill unnecessary processes
scripts=`ps -ef | grep -v "grep" | grep ".config/polybar/.*/scripts/.*" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $scripts
do
    kill -9 $d
    wait
done

colorblocks=`ps -efww | grep -v "grep" | grep "\--colorblocks" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $colorblocks
do
    echo "[-] The colorblocks theme $d is still running, killing it"
    kill -9 $d
    wait
done
trans=`ps -efww | grep -v "grep" | grep "\--trans" | awk -vpid=$$ '$2 != pid { print $2 }'`
for d in $trans
do
    echo "[-] The trans theme $d is still running, killing it"
    kill -9 $d
    wait
done

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "colorblocks" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	#rofi -theme .config/polybar/colorblocks/scripts/rofi/launcher.rasi -show drun -run-command 'sudo -A \{cmd\}'
	#echo "[+] Colorblocks Theme Rofi"
	echo 'rofi -theme ~/.config/polybar/colorblocks/scripts/rofi/launcher.rasi -show drun -run-command' > ~/.sudo-launch
	rofi -theme ~/.config/polybar/colorblocks/scripts/rofi/launcher.rasi -dmenu \
		-password \
		-no-fixed-num-lines \
		-p "$(printf "$1" | sed s/://)"
elif [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "trans" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	#echo "[+] Trans Theme Rofi"
	echo 'rofi -theme ~/.config/polybar/trans/scripts/rofi/launcher.rasi -show drun -run-command' > ~/.sudo-launch
	rofi -theme ~/.config/polybar/trans/scripts/rofi/launcher.rasi -dmenu \
		-password \
		-no-fixed-num-lines \
		-p "$(printf "$1" | sed s/://)"
else
    echo "[-] A polybar theme is not running!"
fi